--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.0
-- Dumped by pg_dump version 9.6.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: workshop
--

CREATE TABLE alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE alembic_version OWNER TO workshop;

--
-- Name: tags; Type: TABLE; Schema: public; Owner: workshop
--

CREATE TABLE tags (
    id uuid NOT NULL,
    name character varying(60)
);


ALTER TABLE tags OWNER TO workshop;

--
-- Name: todo_items; Type: TABLE; Schema: public; Owner: workshop
--

CREATE TABLE todo_items (
    id uuid NOT NULL,
    name character varying(60),
    description text,
    completed boolean,
    created_at timestamp with time zone,
    created_by uuid
);


ALTER TABLE todo_items OWNER TO workshop;

--
-- Name: todo_tags; Type: TABLE; Schema: public; Owner: workshop
--

CREATE TABLE todo_tags (
    id uuid NOT NULL,
    todo_id uuid,
    tag_id uuid
);


ALTER TABLE todo_tags OWNER TO workshop;

--
-- Name: users; Type: TABLE; Schema: public; Owner: workshop
--

CREATE TABLE users (
    id uuid NOT NULL,
    email character varying(255),
    hashed_password character varying(255),
    created_at timestamp with time zone,
    is_active boolean
);


ALTER TABLE users OWNER TO workshop;

--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: workshop
--

COPY alembic_version (version_num) FROM stdin;
7c26bf41534c
\.


--
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: workshop
--

COPY tags (id, name) FROM stdin;
\.


--
-- Data for Name: todo_items; Type: TABLE DATA; Schema: public; Owner: workshop
--

COPY todo_items (id, name, description, completed, created_at, created_by) FROM stdin;
242219c2-c888-4889-b405-0502400ccb8e	Finish workshop	Great stuff	f	2020-02-05 00:30:01.633113+01	\N
\.


--
-- Data for Name: todo_tags; Type: TABLE DATA; Schema: public; Owner: workshop
--

COPY todo_tags (id, todo_id, tag_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: workshop
--

COPY users (id, email, hashed_password, created_at, is_active) FROM stdin;
b90fd170-17d7-433a-93fe-9f4f5bdc8037	admin@kabisa.nl	$2b$12$19Jo0HnQ2j0VHkDleW/ez.EF.gFlVei.QWX7DAgHT/ccRt3AwYGxO	2020-02-05 00:28:25.341052+01	t
\.


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: todo_items todo_items_pkey; Type: CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY todo_items
    ADD CONSTRAINT todo_items_pkey PRIMARY KEY (id);


--
-- Name: todo_tags todo_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY todo_tags
    ADD CONSTRAINT todo_tags_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: ix_tags_name; Type: INDEX; Schema: public; Owner: workshop
--

CREATE UNIQUE INDEX ix_tags_name ON tags USING btree (name);


--
-- Name: ix_todo_items_name; Type: INDEX; Schema: public; Owner: workshop
--

CREATE UNIQUE INDEX ix_todo_items_name ON todo_items USING btree (name);


--
-- Name: ix_todo_tags_tag_id; Type: INDEX; Schema: public; Owner: workshop
--

CREATE INDEX ix_todo_tags_tag_id ON todo_tags USING btree (tag_id);


--
-- Name: ix_todo_tags_todo_id; Type: INDEX; Schema: public; Owner: workshop
--

CREATE INDEX ix_todo_tags_todo_id ON todo_tags USING btree (todo_id);


--
-- Name: ix_users_email; Type: INDEX; Schema: public; Owner: workshop
--

CREATE UNIQUE INDEX ix_users_email ON users USING btree (email);


--
-- Name: todo_items todo_items_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY todo_items
    ADD CONSTRAINT todo_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);


--
-- Name: todo_tags todo_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY todo_tags
    ADD CONSTRAINT todo_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags(id);


--
-- Name: todo_tags todo_tags_todo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: workshop
--

ALTER TABLE ONLY todo_tags
    ADD CONSTRAINT todo_tags_todo_id_fkey FOREIGN KEY (todo_id) REFERENCES todo_items(id);


--
-- PostgreSQL database dump complete
--

